export const environment = {
  firebase: {
    projectId: 'canva-share',
    appId: '1:914595712966:web:6f3617de51337b6d342cc7',
    databaseURL: 'https://canva-share.firebaseio.com',
    storageBucket: 'canva-share.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyDnLdqKBsavxyXBGJ_6N8wpS1XKlgagd_o',
    authDomain: 'canva-share.firebaseapp.com',
    messagingSenderId: '914595712966',
    measurementId: 'G-95JEGSWHCE',
  },
  production: true,
  firebaseConfig: {
    apiKey: 'AIzaSyDnLdqKBsavxyXBGJ_6N8wpS1XKlgagd_o',
    authDomain: 'canva-share.firebaseapp.com',
    databaseURL: 'https://canva-share.firebaseio.com',
    projectId: 'canva-share',
    storageBucket: 'canva-share.appspot.com',
    messagingSenderId: '914595712966',
    appId: '1:914595712966:web:6f3617de51337b6d342cc7',
    measurementId: 'G-95JEGSWHCE',
    url: 'https://canvassocketypescript.herokuapp.com/',
  },
};
